### ISSUE TITLE
環境移行について

### ISSUE THREAD

**Issue by mitcon** [tamura2004/ogisuinote#2]
ogisuinoteをフォークして自環境で構築しようとしています。

firebase.tsに接続先DBの認証周りの情報を記入しているようなので、
新規に作成したfirebaseの認証情報に置き換えたのですが、yarn serve後にずっと
読み込み中のグルグルアイコンから先に進みません。
エラーは特に出ていませんでした。
環境移行に際して他に書き換える必要のある箇所や、必要な設定事項等ありますか？

**Comment by tamura2004** [comment]
ログイン画面のデフォルトメールドメイン取得で、初期設定が必要なややこしいことをしています。元リポジトリの最新commitで関連一式削除していますので、マージして試してみて下さい。
とりあえずログイン画面まではたどり着けるはずです。

**Comment by mitcon** [comment]
ありがとうございます。確認してみます。

**Comment by mitcon** [comment]
すみません、masterブランチですか？
見つけられませんでした。

**Comment by tamura2004** [comment]
すみません、push漏れでした。こちらです。
https://github.com/tamura2004/ogisuinote/commit/b609a619a8a52139fc47c6567579d5ba55307872

**Comment by tamura2004** [comment]
おお、コミットへのリンク貼れた。

**Comment by mitcon** [comment]
ありがとうございます。通常通り使えるようになりました。
